[project]
authors = ["mantasm"]
entry = "lib.sw"
license = "Apache-2.0"
name = "mylib"

[dependencies]
sway_libs = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.22.0" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.1" }
